// استيراد كل النماذج لضمان تسجيلها في Mongoose
import '@/models/Tenant'
import '@/models/User'
import '@/models/Role'
import '@/models/Asset'
import '@/models/WorkOrder'
import '@/models/SparePart'
import '@/models/Employee'
import '@/models/Transaction'
import '@/models/ProductionPlan'
import '@/models/Inventory'
import '@/models/PurchaseOrder'
import '@/models/MaintenanceRequest'
import '@/models/PreventiveMaintenance'
import '@/models/ActivationCode'
import '@/models/Notification'